Traceback (most recent call last):
  File "/Users/hadiji/anaconda3/envs/py39/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/hadiji/anaconda3/envs/py39/lib/python3.9/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/hadiji/anaconda3/envs/py39/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/hadiji/anaconda3/envs/py39/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/hadiji/anaconda3/envs/py39/lib/python3.9/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/hadiji/anaconda3/envs/py39/lib/python3.9/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/hadiji/anaconda3/envs/py39/lib/python3.9/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
model = MLPdeep(hidden_dim=10)
losses = train(model, 
                dataset, 
                N_steps=10000, 
                batch_size=15, 
                lr=.1, 
                save_weights_every=1,
                )

plot_net(model)
plot_data(dataset)
plt.show()

plt.plot(losses)
plt.show()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[6], line 2[0m
[1;32m      1[0m model [38;5;241m=[39m MLPdeep(hidden_dim[38;5;241m=[39m[38;5;241m10[39m)
[0;32m----> 2[0m losses [38;5;241m=[39m [43mtrain[49m[43m([49m[43mmodel[49m[43m,[49m[43m [49m
[1;32m      3[0m [43m                [49m[43mdataset[49m[43m,[49m[43m [49m
[1;32m      4[0m [43m                [49m[43mN_steps[49m[38;5;241;43m=[39;49m[38;5;241;43m10000[39;49m[43m,[49m[43m [49m
[1;32m      5[0m [43m                [49m[43mbatch_size[49m[38;5;241;43m=[39;49m[38;5;241;43m15[39;49m[43m,[49m[43m [49m
[1;32m      6[0m [43m                [49m[43mlr[49m[38;5;241;43m=[39;49m[38;5;241;43m.1[39;49m[43m,[49m[43m [49m
[1;32m      7[0m [43m                [49m[43msave_weights_every[49m[38;5;241;43m=[39;49m[38;5;241;43m1[39;49m[43m,[49m
[1;32m      8[0m [43m                [49m[43m)[49m
[1;32m     10[0m plot_net(model)
[1;32m     11[0m plot_data(dataset)

Cell [0;32mIn[5], line 16[0m, in [0;36mtrain[0;34m(net, dataset, N_steps, batch_size, lr, save_weights_every)[0m
[1;32m     11[0m weights [38;5;241m=[39m []
[1;32m     13[0m [38;5;28;01mfor[39;00m i [38;5;129;01min[39;00m [38;5;28mrange[39m(N_steps): 
[1;32m     14[0m     [38;5;66;03m# YOUR CODE HERE[39;00m
[0;32m---> 16[0m     losses[38;5;241m.[39mappend([43mloss[49m[38;5;241m.[39mdetach()[38;5;241m.[39mnumpy())
[1;32m     18[0m     [38;5;28;01mif[39;00m i [38;5;241m%[39m save_weights_every [38;5;241m==[39m [38;5;241m0[39m [38;5;129;01mand[39;00m (save_weights_every [38;5;241m>[39m [38;5;241m0[39m):
[1;32m     19[0m         [38;5;28;01mwith[39;00m torch[38;5;241m.[39mno_grad():

[0;31mNameError[0m: name 'loss' is not defined

